// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringService.Context;

namespace MonitoringService.Migrations
{
    [DbContext(typeof(StatisticContext))]
    [Migration("20180910100623_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MonitoringService.Model.BusQueueStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("MessageTypeId");

                    b.Property<int>("ObjectCount");

                    b.HasKey("Id");

                    b.HasIndex("MessageTypeId");

                    b.ToTable("BusQueueStatistics");
                });

            modelBuilder.Entity("MonitoringService.Model.MessageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MessageName");

                    b.HasKey("Id");

                    b.ToTable("MessageTypes");

                    b.HasData(
                        new { Id = 1001, MessageName = "Физические лица" }
                    );
                });

            modelBuilder.Entity("MonitoringService.Model.BusQueueStatistic", b =>
                {
                    b.HasOne("MonitoringService.Model.MessageType", "MessageType")
                        .WithMany()
                        .HasForeignKey("MessageTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
